language: python
sudo: false
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy
    - pypy3
install:
    - pip install -U pip setuptools
    - pip install -U zope.testrunner coverage
    - pip install -U -e .[test]
script:
    - coverage run -m zope.testrunner --test-path=src
after_success:
    - pip install coveralls && coveralls
notifications:
    email: false
cache: pip
